---
title: ""
---
<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #337ab7;
}

.navbar-default .navbar-collapse, .navbar-default .navbar-form {
background-color: #337ab7;
}

#Drop-Down Menu Color
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
background-color: #337ab7;
}

.navbar-default {
background-color: #337ab7;
}

.navbar-default .navbar-nav>li>a {
color: white;
font-weight: bold;
}

.navbar-default .navbar-brand {
color: white;
font-weight: bold;
}

</style>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-137778138-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-137778138-1');
</script>

<br>

##Jacky Choi

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicons/css/academicons.min.css"/>

<br>

#### About Me

I graduated from the [Department of Epidemiology](https://www.mailman.columbia.edu/become-student/departments/epidemiology) at Columbia University's Mailman School of Public Health with an Applied Biostatistics certificate. My academic coursework was geared heavily toward biostatistical skills using various statistical programs and languages, and included courses such as "Data Science," "Relational Databases and SQL Programming for Research and Data Science," Analysis of Categorical Data," and "Applied Regression (I and II)." During my time there, I was able to learn, apply, and utilize R, SAS, and SQL.

My experience has involved working with various aspects of data (including data acquisition, cleaning, management, analysis, and reporting) in relation to health data. My goal is to utilize data effectively to create meaningful results in a fast-paced and challenging work environment through the application of various statistical and analytic programs, tools, and languages. Taken together, I believe I am a formidable candidate for data analyst, statistical analyst, and data scientist roles. I am currently seeking these positions, or any that sufficiently develops or hones my: ability to work with and manipulate data to derive meaningful results, analytic mindset, programming/coding capability, statistical skills, and/or knowledge of research methods.

<br>

#### Website

I built this website using R and GitHub (with a bit of CSS and HTML) to showcase some of the projects that I have worked on over the past couple of years. I incorporated projects that highlight my various competencies, including:

* Usage of various statistical programs and/or languages (e.g., R, SAS, SQL)
* Knowledge of how to apply various regression techniques, interpret models, and draw valid statistical conclusions
* Understanding of how to clean, manipulate, and analyze data to derive clear and useful insights
* Fluency in data science skills - EDA, data wrangling, data visualization
* Ability to write scientific or research papers

**You can view my [resume](images2/resume.pdf) for a more in-depth look at my skills.**

<br> 

#### Contact Information

Jacky Choi <br>
Primary Email: [jmc525@cornell.edu](mailto:jmc525@cornell.edu) <br>
Alternate Email: [jmc2392@caa.columbia.edu](mailto:jmc2392@caa.columbia.edu)  
Phone: 917-216-1621

<br>

#### Copyright

Copyright © 2020 Jacky Choi

All rights reserved. This website or any portion thereof may not be reproduced or used in any manner whatsoever
without the express written permission of the author. Note that all projects use hypothetical data, with the exception of the NHANES and NYC Crime projects.

