<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title></title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    SAS Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="NHANES1.html">Alcohol and Smoking Using NHANES</a>
    </li>
    <li>
      <a href="NHANES2.html">Away-From-Home Meals and BMI</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ordinalmodel.html">Analyzing Likert Scale of Depressive Symptoms</a>
    </li>
  </ul>
</li>
<li>
  <a href="resume.html">Resume</a>
</li>
<li>
  <a href="mailto:&lt;jmc2392@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/jmc2392/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">




</div>


<p><br></p>
<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #337ab7;
}

.navbar-default .navbar-collapse, .navbar-default .navbar-form {
background-color: #337ab7;
}

#Drop-Down Menu Color
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
background-color: #337ab7;
}

.navbar-default {
background-color: #337ab7;
}

.navbar-default .navbar-nav>li>a {
color: white;
font-weight: bold;
}

.navbar-default .navbar-brand {
color: white;
font-weight: bold;
}

</style>
<div id="analyzing-likert-scale-of-depressive-symptoms" class="section level2">
<h2>Analyzing Likert Scale of Depressive Symptoms</h2>
<p><br></p>
<div id="skills" class="section level3">
<h3>Skills</h3>
<ul>
<li>Data Analysis</li>
<li>Logistic Regression</li>
<li>R</li>
<li>SAS</li>
</ul>
<p><br></p>
</div>
<div id="packages" class="section level3">
<h3>Packages</h3>
<pre class="r"><code>library(knitr)
library(plotly)</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## 
## Attaching package: &#39;plotly&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<pre class="r"><code>library(ggplot2)
library(MASS)</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:plotly&#39;:
## 
##     select</code></pre>
<pre class="r"><code>library(plyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;plyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:plotly&#39;:
## 
##     arrange, mutate, rename, summarise</code></pre>
<p><br></p>
</div>
<div id="background" class="section level3">
<h3>Background</h3>
<p>At the beginning of the Work-Focused Intervention for Depression (WFID) trial, a baseline survey containing questions about respondents’ level and frequency of various moods was administered. Researchers gathered responses from 90 individuals in the experimental group and now want to determine the ranking of their responses for one survey question that used a Likert scale - specifically, they want to know whether respondents experienced certain depressive symptoms more often than others. Figure 1 displays the survey question being analyzed and Figure 2 displays a sample respondent answer.</p>
<p>Figure 1: Frequency of Various Moods Survey Question <br> <img src = "images2/depressed.jpg" alt="depressed1" style="width:75%; border:1px solid"></p>
<p><br></p>
<p><img src="images2/depressed.jpg" width="75%" style="background-color: #000000; padding:1px; display: inline-block;" /></p>
<p><br></p>
<p>Figure 2: Sample Respondent Answer to Survey Question <br> <img src="images/depressed2.jpg" alt="depressed2" style="width:75%; border:1px solid"></p>
<p><br></p>
</div>
<div id="methods" class="section level3">
<h3>Methods</h3>
<p>I input the respondent answers into a table (group-level format).</p>
<p>In the table shown below:</p>
<ul>
<li><code>Obs</code> is an ID for each row</li>
<li><code>Rating</code> contains the response rating given by each respondent, from 1 to 5</li>
<li><code>Item</code> lists the type of mood being considered</li>
<li><code>Count</code> gives the frequency that each item received for each rating</li>
</ul>
<table>
<caption>Figure 1. Count of Each Mood Item</caption>
<thead>
<tr class="header">
<th align="center">obs</th>
<th align="center">item</th>
<th align="center">rating</th>
<th align="center">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">Depressed</td>
<td align="center">1</td>
<td align="center">22</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">Depressed</td>
<td align="center">2</td>
<td align="center">20</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">Depressed</td>
<td align="center">3</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">Depressed</td>
<td align="center">4</td>
<td align="center">16</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">Depressed</td>
<td align="center">5</td>
<td align="center">14</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">Happy</td>
<td align="center">1</td>
<td align="center">6</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">Happy</td>
<td align="center">2</td>
<td align="center">15</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">Happy</td>
<td align="center">3</td>
<td align="center">20</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">Happy</td>
<td align="center">4</td>
<td align="center">23</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">Happy</td>
<td align="center">5</td>
<td align="center">26</td>
</tr>
<tr class="odd">
<td align="center">11</td>
<td align="center">Hopeless</td>
<td align="center">1</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td align="center">12</td>
<td align="center">Hopeless</td>
<td align="center">2</td>
<td align="center">22</td>
</tr>
<tr class="odd">
<td align="center">13</td>
<td align="center">Hopeless</td>
<td align="center">3</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td align="center">14</td>
<td align="center">Hopeless</td>
<td align="center">4</td>
<td align="center">14</td>
</tr>
<tr class="odd">
<td align="center">15</td>
<td align="center">Hopeless</td>
<td align="center">5</td>
<td align="center">14</td>
</tr>
<tr class="even">
<td align="center">16</td>
<td align="center">Satisfied</td>
<td align="center">1</td>
<td align="center">13</td>
</tr>
<tr class="odd">
<td align="center">17</td>
<td align="center">Satisfied</td>
<td align="center">2</td>
<td align="center">17</td>
</tr>
<tr class="even">
<td align="center">18</td>
<td align="center">Satisfied</td>
<td align="center">3</td>
<td align="center">28</td>
</tr>
<tr class="odd">
<td align="center">19</td>
<td align="center">Satisfied</td>
<td align="center">4</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">20</td>
<td align="center">Satisfied</td>
<td align="center">5</td>
<td align="center">14</td>
</tr>
<tr class="odd">
<td align="center">21</td>
<td align="center">Anxious</td>
<td align="center">1</td>
<td align="center">16</td>
</tr>
<tr class="even">
<td align="center">22</td>
<td align="center">Anxious</td>
<td align="center">2</td>
<td align="center">18</td>
</tr>
<tr class="odd">
<td align="center">23</td>
<td align="center">Anxious</td>
<td align="center">3</td>
<td align="center">22</td>
</tr>
<tr class="even">
<td align="center">24</td>
<td align="center">Anxious</td>
<td align="center">4</td>
<td align="center">19</td>
</tr>
<tr class="odd">
<td align="center">25</td>
<td align="center">Anxious</td>
<td align="center">5</td>
<td align="center">15</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>I ran an ordinal logistic regression model (proportional odds model) on the data to determine the ranking of each item, modeling the independent variable, item, against the response variable, rating. For the reference mood item, I used “Happy.” I assumed that the scale from one response option to another (i.e., Never to Rarely, Rarely to Some of the time, etc.) is the same for all response options; the proportional odds assumption held (p &gt; 0.05) for this model, supporting this. I modeled my parameters over lower-ordered values of the ratings - that is, a larger positive parameter/coefficient indicates respondents’ preference or tendency toward the lower-numbered ratings for that mood item compared to the reference mood item.</p>
<p><br></p>
</div>
<div id="results---sas" class="section level3">
<h3>Results - SAS</h3>
<p>The SAS code and output for the model is provided below.</p>
<p>Figure 3: SAS Code for Logistic Regression Model <br> <img src="images/depressed3.jpg" alt="depressed3" style="width:75%; border:1px solid"></p>
<p><br></p>
<p>Figure 4: Partial SAS Output for Logistic Regression Model <br> <img src="images/depressed4.jpg" alt="depressed4" style="width:75%; border:1px solid"></p>
<p><br></p>
<p>Figure 5: Probabilities of Ratings, By Mood <br> <img src="images/depressed5.jpg" alt="depressed5" style="width:75%; border:1px solid"></p>
<p><br></p>
<p>From Figure 3 in the SAS output above, we can see that the coefficient for the Depressed item is 1.0094, indicating that the log odds of the Depressed item having a lower-numbered rating compared to the Happy item is 1.0094. Recall that a lower-numbered rating indicates that the respondent experienced the mood more frequently. Thus, respondents experienced depressive moods more often than happy moods.</p>
<p>The relative magnitude of the slopes in Figure 4 above imply the ordering of their frequency. <strong>Thus, the order of most frequently experienced mood to least frequently experienced mood among these 90 respondents is depressed, hopeless, anxious, satistfied, and happy.</strong> Note that Figure 4 also gives the odds of a respondent picking a lower-numbered rating for each mood item compared to the “Happy” item.</p>
<p>Figure 5 plots the expected probability of each rating by mood. We can clearly tell, just by viewing the figure, that a respondent is more likely to feel depressed all of the time in the past month rather than feel happy all of the time in the past month.</p>
<p><br></p>
</div>
<div id="results---r" class="section level3">
<h3>Results - R</h3>
<p>We run the same model in R. The R code and output for the model is provided below.</p>
<pre class="r"><code>item &lt;- factor(rep(c(&quot;Happy&quot;, &quot;Depressed&quot;, &quot;Hopeless&quot;, &quot;Satisfied&quot;, &quot;Anxious&quot;), 
        c(90, 90, 90, 90, 90)), 
        levels = c(&quot;Happy&quot;, &quot;Depressed&quot;, &quot;Hopeless&quot;, &quot;Satisfied&quot;, &quot;Anxious&quot;))  

happy &lt;- c(6, 15, 20, 23, 26) # cell counts
depressed &lt;- c(22, 20, 18, 16, 14) # cell counts
hopeless &lt;- c(20, 22, 20, 14, 14) # cell counts
satisfied &lt;- c(13, 17, 28, 18, 14) # cell counts
anxious &lt;- c(16, 18, 22, 19, 15) # cell counts

rating &lt;- c(&quot;All of the time&quot;,&quot;Most of the time&quot;,&quot;Some of the time&quot;,&quot;Rarely&quot;,&quot;Never&quot;)
rating2 &lt;- factor(c(rep(rating, happy), 
                  rep(rating, depressed),
                  rep(rating, hopeless),
                  rep(rating, satisfied),
                  rep(rating, anxious)),
                  levels = rating)

model &lt;- data.frame(item, rating2)

#Ordinal Logistic Regression Model
logmodel &lt;- polr(rating2 ~ item, data = model, Hess = TRUE)
summary(logmodel)</code></pre>
<pre><code>## Call:
## polr(formula = rating2 ~ item, data = model, Hess = TRUE)
## 
## Coefficients:
##                 Value Std. Error t value
## itemDepressed -1.0094     0.2699  -3.739
## itemHopeless  -1.0065     0.2683  -3.751
## itemSatisfied -0.6549     0.2616  -2.503
## itemAnxious   -0.7116     0.2650  -2.686
## 
## Intercepts:
##                                   Value    Std. Error t value 
## All of the time|Most of the time   -2.2909   0.2192   -10.4510
## Most of the time|Some of the time  -1.1943   0.1992    -5.9959
## Some of the time|Rarely            -0.1845   0.1916    -0.9626
## Rarely|Never                        0.8581   0.1981     4.3320
## 
## Residual Deviance: 1423.476 
## AIC: 1439.476</code></pre>
<p><br></p>
<p>Based on the R output above, we can see that the results are the same as those derived from the SAS code. R adds on minus signs to the parameters so that a larger positive parameter/coefficient actually indicates respondents’ preference or tendency toward the HIGHER-numbered ratings for that mood item compared to the reference mood item. For instance, as shown below, exponentiating the coefficient for the Depressed item (-1.0094) gives us 0.3644 while exponentiating the coefficient for the Anxious item (-0.7116) gives us 0.4909 - thus, the odds of the Depressed item having a higher-numbered rating compared to the Happy item is 0.3644 while the odds of the Anxious item having a higher-numbered rating compared to the Happy item is 0.4909.</p>
<pre class="r"><code>exp(coef(logmodel))</code></pre>
<pre><code>## itemDepressed  itemHopeless itemSatisfied   itemAnxious 
##     0.3644238     0.3655091     0.5195137     0.4908442</code></pre>
<p><br></p>
<p>If we find the inverse of the exponentiation of all the coefficients, we can derive the odds of a mood item having a LOWER-numbered rating compared to the Happy item, as shown below. Note that these odds ratios are the same as those derived in Figure 3 using SAS! <strong>The order of most frequently experienced mood to least frequently experienced mood among these 90 respondents remains the same as that derived in SAS - depressed, hopeless, anxious, satistfied, and happy.</strong></p>
<pre class="r"><code>or &lt;- 1 / exp(coef(logmodel))
or</code></pre>
<pre><code>## itemDepressed  itemHopeless itemSatisfied   itemAnxious 
##      2.744058      2.735910      1.924877      2.037306</code></pre>
<p><br></p>
<p>Lastly, we can recreate Figure 5 and plot the expected probability of each rating by mood.</p>
<pre class="r"><code>#Predictions
predict(logmodel, newdata = data.frame(item = &quot;Depressed&quot;), type = &quot;p&quot;)</code></pre>
<pre><code>##  All of the time Most of the time Some of the time           Rarely 
##        0.2172945        0.2366131        0.2413848        0.1708813 
##            Never 
##        0.1338263</code></pre>
<pre class="r"><code>predict(logmodel, newdata = data.frame(item = &quot;Hopeless&quot;), type = &quot;p&quot;)</code></pre>
<pre><code>##  All of the time Most of the time Some of the time           Rarely 
##        0.2167892        0.2363814        0.2414915        0.1711666 
##            Never 
##        0.1341714</code></pre>
<pre class="r"><code>predict(logmodel, newdata = data.frame(item = &quot;Anxious&quot;), type = &quot;p&quot;)</code></pre>
<pre><code>##  All of the time Most of the time Some of the time           Rarely 
##        0.1708929        0.2107209        0.2472091        0.1989226 
##            Never 
##        0.1722544</code></pre>
<pre class="r"><code>predict(logmodel, newdata = data.frame(item = &quot;Satisfied&quot;), type = &quot;p&quot;)</code></pre>
<pre><code>##  All of the time Most of the time Some of the time           Rarely 
##        0.1629993        0.2053115        0.2471686        0.2040211 
##            Never 
##        0.1804995</code></pre>
<pre class="r"><code>predict(logmodel, newdata = data.frame(item = &quot;Happy&quot;), type = &quot;p&quot;)</code></pre>
<pre><code>##  All of the time Most of the time Some of the time           Rarely 
##       0.09187603       0.14060895       0.22153085       0.24824872 
##            Never 
##       0.29773545</code></pre>
<pre class="r"><code>#Probabilities of Rating for Each Mood Item, Plotted
a &lt;- factor(predict(logmodel, newdata = data.frame(item = &quot;Depressed&quot;), type = &quot;p&quot;))
b &lt;- factor(predict(logmodel, newdata = data.frame(item = &quot;Hopeless&quot;), type = &quot;p&quot;))
c &lt;- factor(predict(logmodel, newdata = data.frame(item = &quot;Anxious&quot;), type = &quot;p&quot;))
d &lt;- factor(predict(logmodel, newdata = data.frame(item = &quot;Satisfied&quot;), type = &quot;p&quot;))
e &lt;- factor(predict(logmodel, newdata = data.frame(item = &quot;Happy&quot;), type = &quot;p&quot;))

depcat &lt;- c(&quot;Depressed&quot;, &quot;Depressed&quot;, &quot;Depressed&quot;, &quot;Depressed&quot;, &quot;Depressed&quot;)
hopelesscat &lt;- c(&quot;Hopeless&quot;, &quot;Hopeless&quot;, &quot;Hopeless&quot;, &quot;Hopeless&quot;, &quot;Hopeless&quot;)
anxiouscat &lt;- c(&quot;Anxious&quot;, &quot;Anxious&quot;, &quot;Anxious&quot;, &quot;Anxious&quot;, &quot;Anxious&quot;)
satisfiedcat &lt;- c(&quot;Satisfied&quot;, &quot;Satisfied&quot;, &quot;Satisfied&quot;, &quot;Satisfied&quot;, &quot;Satisfied&quot;)
happycat &lt;- c(&quot;Happy&quot;, &quot;Happy&quot;, &quot;Happy&quot;, &quot;Happy&quot;, &quot;Happy&quot;)

apredict &lt;- data.frame(a, depcat, rating)
apredict &lt;- (plyr::rename(apredict, c(&quot;a&quot;=&quot;value&quot;, &quot;depcat&quot;=&quot;category&quot;)))
bpredict &lt;- data.frame(b, hopelesscat, rating)
bpredict &lt;- (plyr::rename(bpredict, c(&quot;b&quot;=&quot;value&quot;, &quot;hopelesscat&quot;=&quot;category&quot;)))
cpredict &lt;- data.frame(c, anxiouscat, rating)
cpredict &lt;- (plyr::rename(cpredict, c(&quot;c&quot;=&quot;value&quot;, &quot;anxiouscat&quot;=&quot;category&quot;)))
dpredict &lt;- data.frame(d, satisfiedcat, rating)
dpredict &lt;- (plyr::rename(dpredict, c(&quot;d&quot;=&quot;value&quot;, &quot;satisfiedcat&quot;=&quot;category&quot;)))
epredict &lt;- data.frame(e, happycat, rating)
epredict &lt;- (plyr::rename(epredict, c(&quot;e&quot;=&quot;value&quot;, &quot;happycat&quot;=&quot;category&quot;)))

total &lt;- rbind(apredict, bpredict)
total2 &lt;- rbind(total, cpredict)
total3 &lt;- rbind(total2, dpredict)
total4 &lt;- rbind(total3, epredict)

total4$value &lt;- as.numeric(as.character(total4$value))

plot = total4 %&gt;% 
  ggplot(aes(fill = rating, x = category, y = value, color = rating)) +
  geom_bar(stat = &quot;identity&quot;) +
    labs(
    title = &quot;Probability of Each Rating, By Category&quot;,
    x = &quot;Category&quot;,
    y = &quot;Value&quot;
    ) +
  scale_y_continuous(limits=c(0, 1)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = &quot;bottom&quot;)

plot</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="ordinalmodel_files/figure-html/create_factors-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
